/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_niklaskorz_canny_ScriptContext */

#ifndef _Included_de_niklaskorz_canny_ScriptContext
#define _Included_de_niklaskorz_canny_ScriptContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_niklaskorz_canny_ScriptContext
 * Method:    createNativeContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_niklaskorz_canny_ScriptContext_createNativeContext
  (JNIEnv *, jclass);

/*
 * Class:     de_niklaskorz_canny_ScriptContext
 * Method:    eval
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_niklaskorz_canny_ScriptContext_eval
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
